# Generated by Django 4.0.4 on 2022-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='business_email',
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
